version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0.15
    volumes:
      - mqtt-volume:/mosquitto/data
      - mqtt-volume:/mosquitto/log
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '1883:1883'
    networks:
      - chill-network

  postgres:
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./apps/backend/data:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=/run/secrets/chill_postgres_password
    networks:
      - backend-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'backend']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  backend:
    depends_on:
      mqtt:
        condition: service_started
      postgres:
        condition: service_healthy
        restart: true
    image: ghcr.io/ducthuy-ng/dadn-chill-backend:0.6.0
    ports:
      - '3333:3333'
    networks:
      - chill-network
      - backend-network
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=/run/secrets/chill_postgres_password
      - POSTGRES_DB=backend
      - POSTGRES_HOST=postgres
      - FRONTEND_ENDPOINT=https://cg-monitor.duckdns.org
      - MQTT_HOSTNAME=mqtt://mqtt:1883

  ml-server:
    depends_on:
      - mqtt
      - backend
    image: ghcr.io/ducthuy-ng/dadn-chill-ml-server:0.6.0
    environment:
      - MQTT_HOSTNAME=mqtt://mqtt:1883
      - MQTT_INCOMING_TOPIC=chill-topic
      - BACKEND_NOTIFICATION_WEBHOOK=http://backend:3333/webhook/notification-webhook
      - MODEL_FILE_PATH=/app/decision_tree.model
    networks:
      - chill-network

  frontend:
    depends_on:
      - backend
    image: ghcr.io/ducthuy-ng/dadn-chill-frontend:0.6.0
    ports:
      - '4200:80'
    environment:
      - VITE_HOST=https://cg-monitor-internal.duckdns.org

secrets:
  chill_postgres_password:
    external: true

volumes:
  postgres-volume:
  mqtt-volume:

networks:
  chill-network:
  backend-network:
