name: lint-pr

on: [pull_request]

jobs:
  run-linter-and-formatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 16.18
        uses: actions/setup-node@v3
        with:
          node-version: 16.18

      - name: Setup dev
        run: npm run setup:dev

      - name: Test frontend
        run: npm run test:frontend

      - name: Test backend
        run: npm run test:backend

      - name: Test Backend E2E
        run: npm run test:backend-e2e

      - name: Lint check (frontend)
        run: npx nx lint frontend

      - name: Lint check (backend)
        run: npx nx lint backend

      - name: Format check (all file)
        run: npx nx format:check --all
